### ISSUE TITLE
Statefun dependency

### ISSUE THREAD

**Issue by omidb** [ververica/flink-statefun-workshop#1]
Is there any resolver for the Statefun SDK? or should I just publish it locally?

```java
Failed to execute goal on project statefun-workshop-protocol: Could not resolve dependencies for project com.ververica:statefun-workshop-protocol:jar:1.0-SNAPSHOT: Could not find artifact org.apache.flink:statefun-sdk:jar:1.1-SNAPSHOT
```

**Comment by sjwiesman** [comment]
Hi @omidb, 

Currently, you need to install the statefun-repo locally[1]. Once the Flink community releases the first version of stateful functions this project will remain fixed on stable versions. 

[1] githhub.com/apache/flink-statefun
